// Middlegame lessons. Each "move" position comes from the Lichess puzzle database (CC0)
// and was checked with Stockfish: the answer is the engine's best move and clearly better
// than the alternatives, so no good move is marked wrong.
import type { Tutorial } from "@/lib/tutorials-data";

export const MIDDLEGAME_TUTORIALS: Tutorial[] = [
  {
    id: "mg-hanging",
    title: "Hanging Pieces",
    description: "Spot what's undefended and take it. Count before you capture.",
    level: "intermediate",
    topic: "middlegame",
    estimatedMinutes: 5,
    steps: [
      {
        kind: "observe",
        fen: "1k6/pp2bp2/2b1p3/2B1Pp2/1P3P2/P4NP1/3r1RKr/2R5 w - - 7 33",
        title: "Free material",
        body: "A hanging piece is one that is attacked and not defended enough. At club level, most games are decided by pieces left hanging. Before every move, check what your last move and your opponent's last move left undefended, then count: if you have more attackers than they have defenders, the capture usually wins material.",
      },
      {
        kind: "move",
        fen: "1k6/pp2bp2/2b1p3/2B1Pp2/1P3P2/P4NP1/3r1RKr/2R5 w - - 7 33",
        title: "Position 1 of 3",
        body: "White to play. Take the hanging material. Find the piece that isn't properly defended and win it.",
        answer: "g2h2",
        hint: "g2",
      },
      {
        kind: "move",
        fen: "r1b1r1k1/pppp1p1p/5bp1/6BP/8/P7/1PP1Q2P/1R2KBq1 w - - 0 18",
        title: "Position 2 of 3",
        body: "White to play. Take the hanging material. Find the piece that isn't properly defended and win it.",
        answer: "e2e8",
        hint: "e2",
      },
      {
        kind: "move",
        fen: "2r1k2r/1q2bp2/p2p4/1p1P2p1/3Q4/PN4B1/1Pn4P/R4R1K w k - 0 25",
        title: "Position 3 of 3",
        body: "White to play. Take the hanging material. Find the piece that isn't properly defended and win it.",
        answer: "d4h8",
        hint: "d4",
      },
      {
        kind: "observe",
        fen: "2r1k2Q/1q2bp2/p2p4/1p1P2p1/8/PN4B1/1Pn4P/R4R1K b - - 0 25",
        title: "Checks, captures, threats",
        body: "Every move, scan in this order: every check, every capture, every threat, for both sides. It's the habit that stops you hanging pieces and catches your opponent's mistakes.",
      },
    ],
  },
  {
    id: "mg-forks",
    title: "Forks",
    description: "One piece, two targets: win material by attacking twice at once.",
    level: "intermediate",
    topic: "middlegame",
    estimatedMinutes: 6,
    steps: [
      {
        kind: "observe",
        fen: "2r5/2qkbp2/p2p2p1/5b2/1p3N2/8/PPPQ4/1K2R2R w - - 1 27",
        title: "Two threats, one move",
        body: "A fork is a single move that attacks two (or more) things at once. Your opponent can only save one. Knights are famous for forks because their L-shaped jump is hard to see coming, but queens, rooks, bishops, kings and even pawns fork too. The best forks include a check, because then the opponent has no time to move the other piece.",
      },
      {
        kind: "move",
        fen: "2r5/2qkbp2/p2p2p1/5b2/1p3N2/8/PPPQ4/1K2R2R w - - 1 27",
        title: "Position 1 of 3",
        body: "White to play. Find the fork. Look for a move that attacks the king or a big piece and something else at the same time.",
        answer: "e1e7",
        hint: "e1",
      },
      {
        kind: "move",
        fen: "1k3r2/1p3qp1/1n6/1Pp3b1/p1PpP2r/P2Q4/1BR1N3/K2R4 w - - 0 39",
        title: "Position 2 of 3",
        body: "White to play. Find the fork. Look for a move that attacks the king or a big piece and something else at the same time.",
        answer: "d3g3",
        hint: "d3",
      },
      {
        kind: "move",
        fen: "3r2k1/1q5p/p1b3p1/1pP3Q1/1Ppb2P1/P1r2P2/6P1/2R2R1K w - - 0 31",
        title: "Position 3 of 3",
        body: "White to play. Find the fork. Look for a move that attacks the king or a big piece and something else at the same time.",
        answer: "g5d8",
        hint: "g5",
      },
      {
        kind: "observe",
        fen: "3Q2k1/1q5p/p1b3p1/1pP5/1Ppb2P1/P1r2P2/6P1/2R2R1K b - - 0 31",
        title: "Look for loose pieces",
        body: "Before every move, ask: which enemy pieces are undefended, and is the king exposed? Two targets on the same line or a knight's jump apart are a fork waiting to happen.",
      },
    ],
  },
  {
    id: "mg-pins",
    title: "Pins",
    description: "Freeze a piece in front of something more valuable, then win it.",
    level: "intermediate",
    topic: "middlegame",
    estimatedMinutes: 6,
    steps: [
      {
        kind: "observe",
        fen: "2r4r/ppRn1k2/5p2/3pn3/5B1P/6P1/PP2KP2/3R4 w - - 6 29",
        title: "Stuck in place",
        body: "A pin attacks a piece that can't move out of the way without exposing something more valuable behind it. If the piece behind is the king it's an absolute pin: the pinned piece can't legally move at all. Pinned pieces are weak: attack them again, or take advantage of the squares they no longer defend.",
      },
      {
        kind: "move",
        fen: "2r4r/ppRn1k2/5p2/3pn3/5B1P/6P1/PP2KP2/3R4 w - - 6 29",
        title: "Position 1 of 3",
        body: "White to play. Use the pin. A pinned piece isn't really defending anything; find the move that wins because of it.",
        answer: "f4e5",
        hint: "f4",
      },
      {
        kind: "move",
        fen: "4r1k1/3Nr1pp/4Pp1q/1p1p4/pPn5/5Q1P/6R1/5R1K w - - 4 42",
        title: "Position 2 of 3",
        body: "White to play. Use the pin. A pinned piece isn't really defending anything; find the move that wins because of it.",
        answer: "d7f6",
        hint: "d7",
      },
      {
        kind: "move",
        fen: "r7/5Qbk/1q1p3n/p3p3/2P1P3/2P4R/P3B1PP/7K w - - 6 30",
        title: "Position 3 of 3",
        body: "White to play. Use the pin. A pinned piece isn't really defending anything; find the move that wins because of it.",
        answer: "h3h6",
        hint: "h3",
      },
      {
        kind: "observe",
        fen: "r7/5Qbk/1q1p3R/p3p3/2P1P3/2P5/P3B1PP/7K b - - 0 30",
        title: "Pinned pieces don't defend",
        body: "When a piece is pinned, pretend it isn't there when you count defenders. Then pile up on it: a pinned piece attacked twice often falls.",
      },
    ],
  },
  {
    id: "mg-skewers",
    title: "Skewers",
    description: "A pin in reverse: attack the big piece so the one behind it falls.",
    level: "intermediate",
    topic: "middlegame",
    estimatedMinutes: 5,
    steps: [
      {
        kind: "observe",
        fen: "r4rk1/pp2q3/2n3p1/4p1p1/4R1PQ/7R/PPP4P/2K5 w - - 0 26",
        title: "The reverse pin",
        body: "A skewer attacks a valuable piece that has to move, exposing a piece behind it on the same line. It's a pin turned around: the more valuable piece is in front. Queens and kings lined up on a rank, file or diagonal are the classic target.",
      },
      {
        kind: "move",
        fen: "r4rk1/pp2q3/2n3p1/4p1p1/4R1PQ/7R/PPP4P/2K5 w - - 0 26",
        title: "Position 1 of 3",
        body: "White to play. Find the skewer. Look for two enemy pieces on the same line and hit the front one.",
        answer: "h4h8",
        hint: "h4",
      },
      {
        kind: "move",
        fen: "rnb1k2r/1p1p1p1p/p3pp2/8/3NP3/2qB1K2/P4PPP/R2Q3R w kq - 0 13",
        title: "Position 2 of 3",
        body: "White to play. Find the skewer. Look for two enemy pieces on the same line and hit the front one.",
        answer: "a1c1",
        hint: "a1",
      },
      {
        kind: "move",
        fen: "2r1k2r/5pp1/p2qpn2/6N1/1p1P4/7P/PPQ1BP2/2KR3b w k - 0 20",
        title: "Position 3 of 3",
        body: "White to play. Find the skewer. Look for two enemy pieces on the same line and hit the front one.",
        answer: "c2c8",
        hint: "c2",
      },
      {
        kind: "observe",
        fen: "2Q1k2r/5pp1/p2qpn2/6N1/1p1P4/7P/PP2BP2/2KR3b b k - 0 20",
        title: "Lines are dangerous",
        body: "Whenever your king and queen, or queen and rook, stand on the same line, check whether an enemy rook, bishop or queen can reach it.",
      },
    ],
  },
  {
    id: "mg-discovered",
    title: "Discovered Attacks",
    description: "Move one piece to unleash another: two threats in one go.",
    level: "intermediate",
    topic: "middlegame",
    estimatedMinutes: 6,
    steps: [
      {
        kind: "observe",
        fen: "3rr1k1/2p3pp/p1p5/1q6/2Nb4/P3PR1P/1P2Q1PK/3R4 b - - 3 23",
        title: "Unmasking a threat",
        body: "In a discovered attack you move a piece out of the way of a rook, bishop or queen behind it, so two of your pieces attack at once: the one that moved and the one it uncovered. If the uncovered piece gives check (a discovered check), the moving piece can go almost anywhere, even capture something defended.",
      },
      {
        kind: "move",
        fen: "3rr1k1/2p3pp/p1p5/1q6/2Nb4/P3PR1P/1P2Q1PK/3R4 b - - 3 23",
        title: "Position 1 of 3",
        body: "Black to play. Find the discovered attack. Which piece is blocking one of your long-range pieces, and where can it go with a threat of its own?",
        answer: "d4e5",
        hint: "d4",
      },
      {
        kind: "move",
        fen: "2r3k1/p5pp/8/2bq1p2/1r2pB2/1PQp2P1/P4PBP/2RR2K1 b - - 1 31",
        title: "Position 2 of 3",
        body: "Black to play. Find the discovered attack. Which piece is blocking one of your long-range pieces, and where can it go with a threat of its own?",
        answer: "c5f2",
        hint: "c5",
      },
      {
        kind: "move",
        fen: "2kr4/ppq2p2/3b1p1p/3Bn1r1/P7/2P2N1P/1P3PP1/R2Q1RK1 b - - 2 18",
        title: "Position 3 of 3",
        body: "Black to play. Find the discovered attack. Which piece is blocking one of your long-range pieces, and where can it go with a threat of its own?",
        answer: "e5f3",
        hint: "e5",
      },
      {
        kind: "observe",
        fen: "2kr4/ppq2p2/3b1p1p/3B2r1/P7/2P2n1P/1P3PP1/R2Q1RK1 w - - 0 19",
        title: "Watch the battery",
        body: "A piece standing in front of your own rook, bishop or queen is a loaded weapon. Look for a square where moving it creates a second threat.",
      },
    ],
  },
  {
    id: "mg-deflection",
    title: "Deflection",
    description: "Lure a defender away from the job it's doing.",
    level: "intermediate",
    topic: "middlegame",
    estimatedMinutes: 6,
    steps: [
      {
        kind: "observe",
        fen: "2r3k1/2p3p1/p3p2p/1pR1N1q1/3Pb1Pr/P6P/1P2QP1K/5R2 b - - 0 27",
        title: "Overworked defenders",
        body: "Deflection forces an enemy piece away from a square or piece it is guarding, often with a check or a sacrifice. Look for defenders with two jobs: if a piece is guarding both a key square and another piece, it can't do both.",
      },
      {
        kind: "move",
        fen: "2r3k1/2p3p1/p3p2p/1pR1N1q1/3Pb1Pr/P6P/1P2QP1K/5R2 b - - 0 27",
        title: "Position 1 of 3",
        body: "Black to play. Deflect the defender. Find the move that drags a guarding piece away from its duty.",
        answer: "g5f4",
        hint: "g5",
      },
      {
        kind: "move",
        fen: "r5k1/p4ppp/3r4/8/4qR1b/1P2B3/P1P3PP/1RQ3K1 b - - 12 23",
        title: "Position 2 of 3",
        body: "Black to play. Deflect the defender. Find the move that drags a guarding piece away from its duty.",
        answer: "d6d1",
        hint: "d6",
      },
      {
        kind: "move",
        fen: "N1bk2nr/1p1pppbp/1p4p1/q7/4P3/5P2/5PKP/2Q4R w - - 0 17",
        title: "Position 3 of 3",
        body: "White to play. Deflect the defender. Find the move that drags a guarding piece away from its duty.",
        answer: "c1c7",
        hint: "c1",
      },
      {
        kind: "observe",
        fen: "N1bk2nr/1pQpppbp/1p4p1/q7/4P3/5P2/5PKP/7R b - - 1 17",
        title: "Ask what each piece defends",
        body: "Name the job of every enemy defender. A piece doing two jobs is overloaded, and one forcing move can break it.",
      },
    ],
  },
  {
    id: "mg-back-rank",
    title: "The Back Rank",
    description: "A king boxed in by its own pawns is a target on the last rank.",
    level: "intermediate",
    topic: "middlegame",
    estimatedMinutes: 5,
    steps: [
      {
        kind: "observe",
        fen: "4r1k1/p4p1p/5bpB/3B1b2/Q7/8/Pq3PPP/2R3K1 b - - 0 22",
        title: "Trapped by its own pawns",
        body: "A castled king behind three unmoved pawns has no escape square. If an enemy rook or queen reaches the back rank with check and nothing can block or capture it, it's mate. That's why strong players often make luft: a small pawn move like h3 or h6 that gives the king an escape square.",
      },
      {
        kind: "move",
        fen: "4r1k1/p4p1p/5bpB/3B1b2/Q7/8/Pq3PPP/2R3K1 b - - 0 22",
        title: "Position 1 of 3",
        body: "Black to play. Exploit the back rank. Find the move that attacks the weakness on the last rank.",
        answer: "b2c1",
        hint: "b2",
      },
      {
        kind: "move",
        fen: "3R1r1k/1p2QBqp/2b5/2P5/1P2p3/P3P3/5PPP/R5K1 b - - 4 30",
        title: "Position 2 of 3",
        body: "Black to play. Exploit the back rank. Find the move that attacks the weakness on the last rank.",
        answer: "g7a1",
        hint: "g7",
      },
      {
        kind: "move",
        fen: "3N1r1k/1p4pp/p2p1q2/1P6/PBn5/7Q/6PP/4R2K b - - 0 26",
        title: "Position 3 of 3",
        body: "Black to play. Exploit the back rank. Find the move that attacks the weakness on the last rank.",
        answer: "f6f1",
        hint: "f6",
      },
      {
        kind: "observe",
        fen: "3N1r1k/1p4pp/p2p4/1P6/PBn5/7Q/6PP/4Rq1K w - - 1 27",
        title: "Give your own king air",
        body: "In the middlegame, check your own back rank as often as your opponent's. One quiet pawn move can prevent a sudden mate.",
      },
    ],
  },
  {
    id: "mg-king-attack",
    title: "Attacking the King",
    description: "Open lines toward the king and strike before it can hide.",
    level: "intermediate",
    topic: "middlegame",
    estimatedMinutes: 7,
    steps: [
      {
        kind: "observe",
        fen: "r2q1r2/1p3ppk/p7/2p1pP1p/4P1nn/1BN2NR1/PPPQ4/5RK1 b - - 1 21",
        title: "Go for the king",
        body: "When the enemy king has few defenders nearby, an attack can be worth material. Bring more pieces than your opponent can defend with, open files and diagonals toward the king, and use checks and captures so they never get time to regroup. A well-timed sacrifice that rips open the pawn shield is often decisive.",
      },
      {
        kind: "move",
        fen: "r2q1r2/1p3ppk/p7/2p1pP1p/4P1nn/1BN2NR1/PPPQ4/5RK1 b - - 1 21",
        title: "Position 1 of 3",
        body: "Black to play. Find the attacking blow. Checks and captures near the king come first.",
        answer: "h4f3",
        hint: "h4",
      },
      {
        kind: "move",
        fen: "3r1rk1/p3R1p1/2bp1pQp/1p4q1/8/BP6/P4PPP/3R2K1 w - - 2 23",
        title: "Position 2 of 3",
        body: "White to play. Find the attacking blow. Checks and captures near the king come first.",
        answer: "e7g7",
        hint: "e7",
      },
      {
        kind: "move",
        fen: "rn3rk1/pb3qb1/2p1pnQ1/1p4BP/3PN3/4P3/PP3PP1/R3K2R w KQ - 1 19",
        title: "Position 3 of 3",
        body: "White to play. Find the attacking blow. Checks and captures near the king come first.",
        answer: "e4f6",
        hint: "e4",
      },
      {
        kind: "observe",
        fen: "rn3rk1/pb3qb1/2p1pNQ1/1p4BP/3P4/4P3/PP3PP1/R3K2R b KQ - 0 19",
        title: "Count attackers and defenders",
        body: "An attack works when you have more pieces near the king than your opponent can bring to defend. If you don't yet, bring one more piece first.",
      },
    ],
  },
];
