/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FairPlayRouteImport } from './routes/fair-play'
import { Route as CorrespondenceRouteImport } from './routes/correspondence'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ApiDashboardRouteImport } from './routes/api-dashboard'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TacticsIndexRouteImport } from './routes/tactics.index'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as SpectateIndexRouteImport } from './routes/spectate.index'
import { Route as PuzzlesIndexRouteImport } from './routes/puzzles.index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as OpeningsIndexRouteImport } from './routes/openings.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as ForumsIndexRouteImport } from './routes/forums.index'
import { Route as EndgameIndexRouteImport } from './routes/endgame.index'
import { Route as CoachesIndexRouteImport } from './routes/coaches.index'
import { Route as ClubsIndexRouteImport } from './routes/clubs.index'
import { Route as AssistantIndexRouteImport } from './routes/assistant.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as TacticsThemeRouteImport } from './routes/tactics.$theme'
import { Route as StudyStudyIdRouteImport } from './routes/study.$studyId'
import { Route as SpectateGameIdRouteImport } from './routes/spectate.$gameId'
import { Route as PuzzlesStormRouteImport } from './routes/puzzles.storm'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as PlayBotRouteImport } from './routes/play.bot'
import { Route as PlayGameIdRouteImport } from './routes/play.$gameId'
import { Route as OpeningsEcoRouteImport } from './routes/openings.$eco'
import { Route as NewsWriteRouteImport } from './routes/news.write'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as LessonsIdRouteImport } from './routes/lessons.$id'
import { Route as LearnTutorialIdRouteImport } from './routes/learn.$tutorialId'
import { Route as ForumsCategoryRouteImport } from './routes/forums.$category'
import { Route as EndgameIdRouteImport } from './routes/endgame.$id'
import { Route as CoachingDashboardRouteImport } from './routes/coaching.dashboard'
import { Route as CoachesCoachIdRouteImport } from './routes/coaches.$coachId'
import { Route as ClubsSlugRouteImport } from './routes/clubs.$slug'
import { Route as ChallengeIdRouteImport } from './routes/challenge.$id'
import { Route as AssistantThreadIdRouteImport } from './routes/assistant.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminTournamentsRouteImport } from './routes/admin.tournaments'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrgsRouteImport } from './routes/admin.orgs'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminCoachesRouteImport } from './routes/admin.coaches'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as PuzzlesDailyDateRouteImport } from './routes/puzzles.daily.$date'
import { Route as ForumsThreadThreadIdRouteImport } from './routes/forums.thread.$threadId'
import { Route as EmbedKindTokenRouteImport } from './routes/embed.$kind.$token'
import { Route as ApiHealthAiRouteImport } from './routes/api/health/ai'
import { Route as ApiCronTickRouteImport } from './routes/api/cron/tick'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as ApiPublicV1WebhooksRouteImport } from './routes/api/public/v1/webhooks'
import { Route as ApiPublicV1TournamentsRouteImport } from './routes/api/public/v1/tournaments'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack.webhook'
import { Route as ApiPublicV1WebhooksRetrySweepRouteImport } from './routes/api/public/v1/webhooks.retry-sweep'
import { Route as ApiPublicV1WebhooksIdRouteImport } from './routes/api/public/v1/webhooks.$id'
import { Route as ApiPublicV1TournamentsSweepRouteImport } from './routes/api/public/v1/tournaments.sweep'
import { Route as ApiPublicV1EmbedTokenRouteImport } from './routes/api/public/v1/embed.token'
import { Route as ApiPublicV1CorrespondenceSweepRouteImport } from './routes/api/public/v1/correspondence.sweep'
import { Route as ApiPublicV1ClassesSessionRouteImport } from './routes/api/public/v1/classes.session'
import { Route as ApiPublicV1UsersUsernameRatingRouteImport } from './routes/api/public/v1/users.$username.rating'
import { Route as ApiPublicV1UsersUsernameGamesRouteImport } from './routes/api/public/v1/users.$username.games'
import { Route as ApiPublicV1TournamentsIdStandingsRouteImport } from './routes/api/public/v1/tournaments.$id.standings'
import { Route as ApiPublicV1EmbedTokenTokenRouteImport } from './routes/api/public/v1/embed.token.$token'
import { Route as ApiPublicV1ClassesSessionIdStudentsRouteImport } from './routes/api/public/v1/classes.session.$id.students'
import { Route as ApiPublicV1ClassesSessionIdSetPositionRouteImport } from './routes/api/public/v1/classes.session.$id.set-position'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FairPlayRoute = FairPlayRouteImport.update({
  id: '/fair-play',
  path: '/fair-play',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondenceRoute = CorrespondenceRouteImport.update({
  id: '/correspondence',
  path: '/correspondence',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api-dashboard',
  path: '/api-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticsIndexRoute = TacticsIndexRouteImport.update({
  id: '/tactics/',
  path: '/tactics/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectateIndexRoute = SpectateIndexRouteImport.update({
  id: '/spectate/',
  path: '/spectate/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesIndexRoute = PuzzlesIndexRouteImport.update({
  id: '/puzzles/',
  path: '/puzzles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsIndexRoute = OpeningsIndexRouteImport.update({
  id: '/openings/',
  path: '/openings/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsIndexRoute = ForumsIndexRouteImport.update({
  id: '/forums/',
  path: '/forums/',
  getParentRoute: () => rootRouteImport,
} as any)
const EndgameIndexRoute = EndgameIndexRouteImport.update({
  id: '/endgame/',
  path: '/endgame/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesIndexRoute = CoachesIndexRouteImport.update({
  id: '/coaches/',
  path: '/coaches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticsThemeRoute = TacticsThemeRouteImport.update({
  id: '/tactics/$theme',
  path: '/tactics/$theme',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyStudyIdRoute = StudyStudyIdRouteImport.update({
  id: '/study/$studyId',
  path: '/study/$studyId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectateGameIdRoute = SpectateGameIdRouteImport.update({
  id: '/spectate/$gameId',
  path: '/spectate/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesStormRoute = PuzzlesStormRouteImport.update({
  id: '/puzzles/storm',
  path: '/puzzles/storm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBotRoute = PlayBotRouteImport.update({
  id: '/play/bot',
  path: '/play/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsEcoRoute = OpeningsEcoRouteImport.update({
  id: '/openings/$eco',
  path: '/openings/$eco',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsWriteRoute = NewsWriteRouteImport.update({
  id: '/news/write',
  path: '/news/write',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTutorialIdRoute = LearnTutorialIdRouteImport.update({
  id: '/learn/$tutorialId',
  path: '/learn/$tutorialId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsCategoryRoute = ForumsCategoryRouteImport.update({
  id: '/forums/$category',
  path: '/forums/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const EndgameIdRoute = EndgameIdRouteImport.update({
  id: '/endgame/$id',
  path: '/endgame/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingDashboardRoute = CoachingDashboardRouteImport.update({
  id: '/coaching/dashboard',
  path: '/coaching/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesCoachIdRoute = CoachesCoachIdRouteImport.update({
  id: '/coaches/$coachId',
  path: '/coaches/$coachId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsSlugRoute = ClubsSlugRouteImport.update({
  id: '/clubs/$slug',
  path: '/clubs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeIdRoute = ChallengeIdRouteImport.update({
  id: '/challenge/$id',
  path: '/challenge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantThreadIdRoute = AssistantThreadIdRouteImport.update({
  id: '/assistant/$threadId',
  path: '/assistant/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgsRoute = AdminOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachesRoute = AdminCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const PuzzlesDailyDateRoute = PuzzlesDailyDateRouteImport.update({
  id: '/puzzles/daily/$date',
  path: '/puzzles/daily/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsThreadThreadIdRoute = ForumsThreadThreadIdRouteImport.update({
  id: '/forums/thread/$threadId',
  path: '/forums/thread/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedKindTokenRoute = EmbedKindTokenRouteImport.update({
  id: '/embed/$kind/$token',
  path: '/embed/$kind/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthAiRoute = ApiHealthAiRouteImport.update({
  id: '/api/health/ai',
  path: '/api/health/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTickRoute = ApiCronTickRouteImport.update({
  id: '/api/cron/tick',
  path: '/api/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicV1WebhooksRoute = ApiPublicV1WebhooksRouteImport.update({
  id: '/api/public/v1/webhooks',
  path: '/api/public/v1/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1TournamentsRoute = ApiPublicV1TournamentsRouteImport.update({
  id: '/api/public/v1/tournaments',
  path: '/api/public/v1/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1WebhooksRetrySweepRoute =
  ApiPublicV1WebhooksRetrySweepRouteImport.update({
    id: '/retry-sweep',
    path: '/retry-sweep',
    getParentRoute: () => ApiPublicV1WebhooksRoute,
  } as any)
const ApiPublicV1WebhooksIdRoute = ApiPublicV1WebhooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1WebhooksRoute,
} as any)
const ApiPublicV1TournamentsSweepRoute =
  ApiPublicV1TournamentsSweepRouteImport.update({
    id: '/sweep',
    path: '/sweep',
    getParentRoute: () => ApiPublicV1TournamentsRoute,
  } as any)
const ApiPublicV1EmbedTokenRoute = ApiPublicV1EmbedTokenRouteImport.update({
  id: '/api/public/v1/embed/token',
  path: '/api/public/v1/embed/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CorrespondenceSweepRoute =
  ApiPublicV1CorrespondenceSweepRouteImport.update({
    id: '/api/public/v1/correspondence/sweep',
    path: '/api/public/v1/correspondence/sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ClassesSessionRoute =
  ApiPublicV1ClassesSessionRouteImport.update({
    id: '/api/public/v1/classes/session',
    path: '/api/public/v1/classes/session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1UsersUsernameRatingRoute =
  ApiPublicV1UsersUsernameRatingRouteImport.update({
    id: '/api/public/v1/users/$username/rating',
    path: '/api/public/v1/users/$username/rating',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1UsersUsernameGamesRoute =
  ApiPublicV1UsersUsernameGamesRouteImport.update({
    id: '/api/public/v1/users/$username/games',
    path: '/api/public/v1/users/$username/games',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1TournamentsIdStandingsRoute =
  ApiPublicV1TournamentsIdStandingsRouteImport.update({
    id: '/$id/standings',
    path: '/$id/standings',
    getParentRoute: () => ApiPublicV1TournamentsRoute,
  } as any)
const ApiPublicV1EmbedTokenTokenRoute =
  ApiPublicV1EmbedTokenTokenRouteImport.update({
    id: '/$token',
    path: '/$token',
    getParentRoute: () => ApiPublicV1EmbedTokenRoute,
  } as any)
const ApiPublicV1ClassesSessionIdStudentsRoute =
  ApiPublicV1ClassesSessionIdStudentsRouteImport.update({
    id: '/$id/students',
    path: '/$id/students',
    getParentRoute: () => ApiPublicV1ClassesSessionRoute,
  } as any)
const ApiPublicV1ClassesSessionIdSetPositionRoute =
  ApiPublicV1ClassesSessionIdSetPositionRouteImport.update({
    id: '/$id/set-position',
    path: '/$id/set-position',
    getParentRoute: () => ApiPublicV1ClassesSessionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/api-dashboard': typeof ApiDashboardRoute
  '/billing': typeof BillingRoute
  '/correspondence': typeof CorrespondenceRoute
  '/fair-play': typeof FairPlayRoute
  '/feed': typeof FeedRoute
  '/insights': typeof InsightsRoute
  '/invite': typeof InviteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/policy': typeof PolicyRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tv': typeof TvRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/challenge/$id': typeof ChallengeIdRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/coaches/$coachId': typeof CoachesCoachIdRoute
  '/coaching/dashboard': typeof CoachingDashboardRoute
  '/endgame/$id': typeof EndgameIdRoute
  '/forums/$category': typeof ForumsCategoryRoute
  '/learn/$tutorialId': typeof LearnTutorialIdRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/write': typeof NewsWriteRoute
  '/openings/$eco': typeof OpeningsEcoRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/play/bot': typeof PlayBotRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/puzzles/storm': typeof PuzzlesStormRoute
  '/spectate/$gameId': typeof SpectateGameIdRoute
  '/study/$studyId': typeof StudyStudyIdRoute
  '/tactics/$theme': typeof TacticsThemeRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/assistant/': typeof AssistantIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/coaches/': typeof CoachesIndexRoute
  '/endgame/': typeof EndgameIndexRoute
  '/forums/': typeof ForumsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/openings/': typeof OpeningsIndexRoute
  '/play/': typeof PlayIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/spectate/': typeof SpectateIndexRoute
  '/study/': typeof StudyIndexRoute
  '/tactics/': typeof TacticsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/health/ai': typeof ApiHealthAiRoute
  '/embed/$kind/$token': typeof EmbedKindTokenRoute
  '/forums/thread/$threadId': typeof ForumsThreadThreadIdRoute
  '/puzzles/daily/$date': typeof PuzzlesDailyDateRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/v1/tournaments': typeof ApiPublicV1TournamentsRouteWithChildren
  '/api/public/v1/webhooks': typeof ApiPublicV1WebhooksRouteWithChildren
  '/api/public/v1/classes/session': typeof ApiPublicV1ClassesSessionRouteWithChildren
  '/api/public/v1/correspondence/sweep': typeof ApiPublicV1CorrespondenceSweepRoute
  '/api/public/v1/embed/token': typeof ApiPublicV1EmbedTokenRouteWithChildren
  '/api/public/v1/tournaments/sweep': typeof ApiPublicV1TournamentsSweepRoute
  '/api/public/v1/webhooks/$id': typeof ApiPublicV1WebhooksIdRoute
  '/api/public/v1/webhooks/retry-sweep': typeof ApiPublicV1WebhooksRetrySweepRoute
  '/api/public/v1/embed/token/$token': typeof ApiPublicV1EmbedTokenTokenRoute
  '/api/public/v1/tournaments/$id/standings': typeof ApiPublicV1TournamentsIdStandingsRoute
  '/api/public/v1/users/$username/games': typeof ApiPublicV1UsersUsernameGamesRoute
  '/api/public/v1/users/$username/rating': typeof ApiPublicV1UsersUsernameRatingRoute
  '/api/public/v1/classes/session/$id/set-position': typeof ApiPublicV1ClassesSessionIdSetPositionRoute
  '/api/public/v1/classes/session/$id/students': typeof ApiPublicV1ClassesSessionIdStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/api-dashboard': typeof ApiDashboardRoute
  '/billing': typeof BillingRoute
  '/correspondence': typeof CorrespondenceRoute
  '/fair-play': typeof FairPlayRoute
  '/feed': typeof FeedRoute
  '/insights': typeof InsightsRoute
  '/invite': typeof InviteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/policy': typeof PolicyRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tv': typeof TvRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/challenge/$id': typeof ChallengeIdRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/coaches/$coachId': typeof CoachesCoachIdRoute
  '/coaching/dashboard': typeof CoachingDashboardRoute
  '/endgame/$id': typeof EndgameIdRoute
  '/forums/$category': typeof ForumsCategoryRoute
  '/learn/$tutorialId': typeof LearnTutorialIdRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/write': typeof NewsWriteRoute
  '/openings/$eco': typeof OpeningsEcoRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/play/bot': typeof PlayBotRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/puzzles/storm': typeof PuzzlesStormRoute
  '/spectate/$gameId': typeof SpectateGameIdRoute
  '/study/$studyId': typeof StudyStudyIdRoute
  '/tactics/$theme': typeof TacticsThemeRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin': typeof AdminIndexRoute
  '/assistant': typeof AssistantIndexRoute
  '/clubs': typeof ClubsIndexRoute
  '/coaches': typeof CoachesIndexRoute
  '/endgame': typeof EndgameIndexRoute
  '/forums': typeof ForumsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/news': typeof NewsIndexRoute
  '/openings': typeof OpeningsIndexRoute
  '/play': typeof PlayIndexRoute
  '/puzzles': typeof PuzzlesIndexRoute
  '/spectate': typeof SpectateIndexRoute
  '/study': typeof StudyIndexRoute
  '/tactics': typeof TacticsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/health/ai': typeof ApiHealthAiRoute
  '/embed/$kind/$token': typeof EmbedKindTokenRoute
  '/forums/thread/$threadId': typeof ForumsThreadThreadIdRoute
  '/puzzles/daily/$date': typeof PuzzlesDailyDateRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/v1/tournaments': typeof ApiPublicV1TournamentsRouteWithChildren
  '/api/public/v1/webhooks': typeof ApiPublicV1WebhooksRouteWithChildren
  '/api/public/v1/classes/session': typeof ApiPublicV1ClassesSessionRouteWithChildren
  '/api/public/v1/correspondence/sweep': typeof ApiPublicV1CorrespondenceSweepRoute
  '/api/public/v1/embed/token': typeof ApiPublicV1EmbedTokenRouteWithChildren
  '/api/public/v1/tournaments/sweep': typeof ApiPublicV1TournamentsSweepRoute
  '/api/public/v1/webhooks/$id': typeof ApiPublicV1WebhooksIdRoute
  '/api/public/v1/webhooks/retry-sweep': typeof ApiPublicV1WebhooksRetrySweepRoute
  '/api/public/v1/embed/token/$token': typeof ApiPublicV1EmbedTokenTokenRoute
  '/api/public/v1/tournaments/$id/standings': typeof ApiPublicV1TournamentsIdStandingsRoute
  '/api/public/v1/users/$username/games': typeof ApiPublicV1UsersUsernameGamesRoute
  '/api/public/v1/users/$username/rating': typeof ApiPublicV1UsersUsernameRatingRoute
  '/api/public/v1/classes/session/$id/set-position': typeof ApiPublicV1ClassesSessionIdSetPositionRoute
  '/api/public/v1/classes/session/$id/students': typeof ApiPublicV1ClassesSessionIdStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/api-dashboard': typeof ApiDashboardRoute
  '/billing': typeof BillingRoute
  '/correspondence': typeof CorrespondenceRoute
  '/fair-play': typeof FairPlayRoute
  '/feed': typeof FeedRoute
  '/insights': typeof InsightsRoute
  '/invite': typeof InviteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/policy': typeof PolicyRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tv': typeof TvRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/challenge/$id': typeof ChallengeIdRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/coaches/$coachId': typeof CoachesCoachIdRoute
  '/coaching/dashboard': typeof CoachingDashboardRoute
  '/endgame/$id': typeof EndgameIdRoute
  '/forums/$category': typeof ForumsCategoryRoute
  '/learn/$tutorialId': typeof LearnTutorialIdRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/write': typeof NewsWriteRoute
  '/openings/$eco': typeof OpeningsEcoRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/play/bot': typeof PlayBotRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/puzzles/storm': typeof PuzzlesStormRoute
  '/spectate/$gameId': typeof SpectateGameIdRoute
  '/study/$studyId': typeof StudyStudyIdRoute
  '/tactics/$theme': typeof TacticsThemeRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/assistant/': typeof AssistantIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/coaches/': typeof CoachesIndexRoute
  '/endgame/': typeof EndgameIndexRoute
  '/forums/': typeof ForumsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/openings/': typeof OpeningsIndexRoute
  '/play/': typeof PlayIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/spectate/': typeof SpectateIndexRoute
  '/study/': typeof StudyIndexRoute
  '/tactics/': typeof TacticsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/health/ai': typeof ApiHealthAiRoute
  '/embed/$kind/$token': typeof EmbedKindTokenRoute
  '/forums/thread/$threadId': typeof ForumsThreadThreadIdRoute
  '/puzzles/daily/$date': typeof PuzzlesDailyDateRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/v1/tournaments': typeof ApiPublicV1TournamentsRouteWithChildren
  '/api/public/v1/webhooks': typeof ApiPublicV1WebhooksRouteWithChildren
  '/api/public/v1/classes/session': typeof ApiPublicV1ClassesSessionRouteWithChildren
  '/api/public/v1/correspondence/sweep': typeof ApiPublicV1CorrespondenceSweepRoute
  '/api/public/v1/embed/token': typeof ApiPublicV1EmbedTokenRouteWithChildren
  '/api/public/v1/tournaments/sweep': typeof ApiPublicV1TournamentsSweepRoute
  '/api/public/v1/webhooks/$id': typeof ApiPublicV1WebhooksIdRoute
  '/api/public/v1/webhooks/retry-sweep': typeof ApiPublicV1WebhooksRetrySweepRoute
  '/api/public/v1/embed/token/$token': typeof ApiPublicV1EmbedTokenTokenRoute
  '/api/public/v1/tournaments/$id/standings': typeof ApiPublicV1TournamentsIdStandingsRoute
  '/api/public/v1/users/$username/games': typeof ApiPublicV1UsersUsernameGamesRoute
  '/api/public/v1/users/$username/rating': typeof ApiPublicV1UsersUsernameRatingRoute
  '/api/public/v1/classes/session/$id/set-position': typeof ApiPublicV1ClassesSessionIdSetPositionRoute
  '/api/public/v1/classes/session/$id/students': typeof ApiPublicV1ClassesSessionIdStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/analysis'
    | '/api-dashboard'
    | '/billing'
    | '/correspondence'
    | '/fair-play'
    | '/feed'
    | '/insights'
    | '/invite'
    | '/leaderboard'
    | '/lobby'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/policy'
    | '/privacy'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/settings'
    | '/support'
    | '/terms'
    | '/tv'
    | '/admin/audit-log'
    | '/admin/coaches'
    | '/admin/games'
    | '/admin/orgs'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/tournaments'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/challenge/$id'
    | '/clubs/$slug'
    | '/coaches/$coachId'
    | '/coaching/dashboard'
    | '/endgame/$id'
    | '/forums/$category'
    | '/learn/$tutorialId'
    | '/lessons/$id'
    | '/news/$slug'
    | '/news/write'
    | '/openings/$eco'
    | '/play/$gameId'
    | '/play/bot'
    | '/profile/$username'
    | '/puzzles/storm'
    | '/spectate/$gameId'
    | '/study/$studyId'
    | '/tactics/$theme'
    | '/tournaments/$id'
    | '/admin/'
    | '/assistant/'
    | '/clubs/'
    | '/coaches/'
    | '/endgame/'
    | '/forums/'
    | '/learn/'
    | '/lessons/'
    | '/news/'
    | '/openings/'
    | '/play/'
    | '/puzzles/'
    | '/spectate/'
    | '/study/'
    | '/tactics/'
    | '/tournaments/'
    | '/admin/users/$userId'
    | '/api/cron/tick'
    | '/api/health/ai'
    | '/embed/$kind/$token'
    | '/forums/thread/$threadId'
    | '/puzzles/daily/$date'
    | '/admin/users/'
    | '/api/public/paystack/webhook'
    | '/api/public/v1/tournaments'
    | '/api/public/v1/webhooks'
    | '/api/public/v1/classes/session'
    | '/api/public/v1/correspondence/sweep'
    | '/api/public/v1/embed/token'
    | '/api/public/v1/tournaments/sweep'
    | '/api/public/v1/webhooks/$id'
    | '/api/public/v1/webhooks/retry-sweep'
    | '/api/public/v1/embed/token/$token'
    | '/api/public/v1/tournaments/$id/standings'
    | '/api/public/v1/users/$username/games'
    | '/api/public/v1/users/$username/rating'
    | '/api/public/v1/classes/session/$id/set-position'
    | '/api/public/v1/classes/session/$id/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analysis'
    | '/api-dashboard'
    | '/billing'
    | '/correspondence'
    | '/fair-play'
    | '/feed'
    | '/insights'
    | '/invite'
    | '/leaderboard'
    | '/lobby'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/policy'
    | '/privacy'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/settings'
    | '/support'
    | '/terms'
    | '/tv'
    | '/admin/audit-log'
    | '/admin/coaches'
    | '/admin/games'
    | '/admin/orgs'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/tournaments'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/challenge/$id'
    | '/clubs/$slug'
    | '/coaches/$coachId'
    | '/coaching/dashboard'
    | '/endgame/$id'
    | '/forums/$category'
    | '/learn/$tutorialId'
    | '/lessons/$id'
    | '/news/$slug'
    | '/news/write'
    | '/openings/$eco'
    | '/play/$gameId'
    | '/play/bot'
    | '/profile/$username'
    | '/puzzles/storm'
    | '/spectate/$gameId'
    | '/study/$studyId'
    | '/tactics/$theme'
    | '/tournaments/$id'
    | '/admin'
    | '/assistant'
    | '/clubs'
    | '/coaches'
    | '/endgame'
    | '/forums'
    | '/learn'
    | '/lessons'
    | '/news'
    | '/openings'
    | '/play'
    | '/puzzles'
    | '/spectate'
    | '/study'
    | '/tactics'
    | '/tournaments'
    | '/admin/users/$userId'
    | '/api/cron/tick'
    | '/api/health/ai'
    | '/embed/$kind/$token'
    | '/forums/thread/$threadId'
    | '/puzzles/daily/$date'
    | '/admin/users'
    | '/api/public/paystack/webhook'
    | '/api/public/v1/tournaments'
    | '/api/public/v1/webhooks'
    | '/api/public/v1/classes/session'
    | '/api/public/v1/correspondence/sweep'
    | '/api/public/v1/embed/token'
    | '/api/public/v1/tournaments/sweep'
    | '/api/public/v1/webhooks/$id'
    | '/api/public/v1/webhooks/retry-sweep'
    | '/api/public/v1/embed/token/$token'
    | '/api/public/v1/tournaments/$id/standings'
    | '/api/public/v1/users/$username/games'
    | '/api/public/v1/users/$username/rating'
    | '/api/public/v1/classes/session/$id/set-position'
    | '/api/public/v1/classes/session/$id/students'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/analysis'
    | '/api-dashboard'
    | '/billing'
    | '/correspondence'
    | '/fair-play'
    | '/feed'
    | '/insights'
    | '/invite'
    | '/leaderboard'
    | '/lobby'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/policy'
    | '/privacy'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/settings'
    | '/support'
    | '/terms'
    | '/tv'
    | '/admin/audit-log'
    | '/admin/coaches'
    | '/admin/games'
    | '/admin/orgs'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/tournaments'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/challenge/$id'
    | '/clubs/$slug'
    | '/coaches/$coachId'
    | '/coaching/dashboard'
    | '/endgame/$id'
    | '/forums/$category'
    | '/learn/$tutorialId'
    | '/lessons/$id'
    | '/news/$slug'
    | '/news/write'
    | '/openings/$eco'
    | '/play/$gameId'
    | '/play/bot'
    | '/profile/$username'
    | '/puzzles/storm'
    | '/spectate/$gameId'
    | '/study/$studyId'
    | '/tactics/$theme'
    | '/tournaments/$id'
    | '/admin/'
    | '/assistant/'
    | '/clubs/'
    | '/coaches/'
    | '/endgame/'
    | '/forums/'
    | '/learn/'
    | '/lessons/'
    | '/news/'
    | '/openings/'
    | '/play/'
    | '/puzzles/'
    | '/spectate/'
    | '/study/'
    | '/tactics/'
    | '/tournaments/'
    | '/admin/users/$userId'
    | '/api/cron/tick'
    | '/api/health/ai'
    | '/embed/$kind/$token'
    | '/forums/thread/$threadId'
    | '/puzzles/daily/$date'
    | '/admin/users/'
    | '/api/public/paystack/webhook'
    | '/api/public/v1/tournaments'
    | '/api/public/v1/webhooks'
    | '/api/public/v1/classes/session'
    | '/api/public/v1/correspondence/sweep'
    | '/api/public/v1/embed/token'
    | '/api/public/v1/tournaments/sweep'
    | '/api/public/v1/webhooks/$id'
    | '/api/public/v1/webhooks/retry-sweep'
    | '/api/public/v1/embed/token/$token'
    | '/api/public/v1/tournaments/$id/standings'
    | '/api/public/v1/users/$username/games'
    | '/api/public/v1/users/$username/rating'
    | '/api/public/v1/classes/session/$id/set-position'
    | '/api/public/v1/classes/session/$id/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalysisRoute: typeof AnalysisRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  BillingRoute: typeof BillingRoute
  CorrespondenceRoute: typeof CorrespondenceRoute
  FairPlayRoute: typeof FairPlayRoute
  FeedRoute: typeof FeedRoute
  InsightsRoute: typeof InsightsRoute
  InviteRoute: typeof InviteRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LobbyRoute: typeof LobbyRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PolicyRoute: typeof PolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TvRoute: typeof TvRoute
  ApiChatRoute: typeof ApiChatRoute
  AssistantThreadIdRoute: typeof AssistantThreadIdRoute
  ChallengeIdRoute: typeof ChallengeIdRoute
  ClubsSlugRoute: typeof ClubsSlugRoute
  CoachesCoachIdRoute: typeof CoachesCoachIdRoute
  CoachingDashboardRoute: typeof CoachingDashboardRoute
  EndgameIdRoute: typeof EndgameIdRoute
  ForumsCategoryRoute: typeof ForumsCategoryRoute
  LearnTutorialIdRoute: typeof LearnTutorialIdRoute
  LessonsIdRoute: typeof LessonsIdRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsWriteRoute: typeof NewsWriteRoute
  OpeningsEcoRoute: typeof OpeningsEcoRoute
  PlayGameIdRoute: typeof PlayGameIdRoute
  PlayBotRoute: typeof PlayBotRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  PuzzlesStormRoute: typeof PuzzlesStormRoute
  SpectateGameIdRoute: typeof SpectateGameIdRoute
  StudyStudyIdRoute: typeof StudyStudyIdRoute
  TacticsThemeRoute: typeof TacticsThemeRoute
  TournamentsIdRoute: typeof TournamentsIdRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
  CoachesIndexRoute: typeof CoachesIndexRoute
  EndgameIndexRoute: typeof EndgameIndexRoute
  ForumsIndexRoute: typeof ForumsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  OpeningsIndexRoute: typeof OpeningsIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  PuzzlesIndexRoute: typeof PuzzlesIndexRoute
  SpectateIndexRoute: typeof SpectateIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
  TacticsIndexRoute: typeof TacticsIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  ApiCronTickRoute: typeof ApiCronTickRoute
  ApiHealthAiRoute: typeof ApiHealthAiRoute
  EmbedKindTokenRoute: typeof EmbedKindTokenRoute
  ForumsThreadThreadIdRoute: typeof ForumsThreadThreadIdRoute
  PuzzlesDailyDateRoute: typeof PuzzlesDailyDateRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicV1TournamentsRoute: typeof ApiPublicV1TournamentsRouteWithChildren
  ApiPublicV1WebhooksRoute: typeof ApiPublicV1WebhooksRouteWithChildren
  ApiPublicV1ClassesSessionRoute: typeof ApiPublicV1ClassesSessionRouteWithChildren
  ApiPublicV1CorrespondenceSweepRoute: typeof ApiPublicV1CorrespondenceSweepRoute
  ApiPublicV1EmbedTokenRoute: typeof ApiPublicV1EmbedTokenRouteWithChildren
  ApiPublicV1UsersUsernameGamesRoute: typeof ApiPublicV1UsersUsernameGamesRoute
  ApiPublicV1UsersUsernameRatingRoute: typeof ApiPublicV1UsersUsernameRatingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fair-play': {
      id: '/fair-play'
      path: '/fair-play'
      fullPath: '/fair-play'
      preLoaderRoute: typeof FairPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondence': {
      id: '/correspondence'
      path: '/correspondence'
      fullPath: '/correspondence'
      preLoaderRoute: typeof CorrespondenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-dashboard': {
      id: '/api-dashboard'
      path: '/api-dashboard'
      fullPath: '/api-dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactics/': {
      id: '/tactics/'
      path: '/tactics'
      fullPath: '/tactics/'
      preLoaderRoute: typeof TacticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectate/': {
      id: '/spectate/'
      path: '/spectate'
      fullPath: '/spectate/'
      preLoaderRoute: typeof SpectateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/': {
      id: '/puzzles/'
      path: '/puzzles'
      fullPath: '/puzzles/'
      preLoaderRoute: typeof PuzzlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings/': {
      id: '/openings/'
      path: '/openings'
      fullPath: '/openings/'
      preLoaderRoute: typeof OpeningsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/': {
      id: '/forums/'
      path: '/forums'
      fullPath: '/forums/'
      preLoaderRoute: typeof ForumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endgame/': {
      id: '/endgame/'
      path: '/endgame'
      fullPath: '/endgame/'
      preLoaderRoute: typeof EndgameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/': {
      id: '/coaches/'
      path: '/coaches'
      fullPath: '/coaches/'
      preLoaderRoute: typeof CoachesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactics/$theme': {
      id: '/tactics/$theme'
      path: '/tactics/$theme'
      fullPath: '/tactics/$theme'
      preLoaderRoute: typeof TacticsThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$studyId': {
      id: '/study/$studyId'
      path: '/study/$studyId'
      fullPath: '/study/$studyId'
      preLoaderRoute: typeof StudyStudyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectate/$gameId': {
      id: '/spectate/$gameId'
      path: '/spectate/$gameId'
      fullPath: '/spectate/$gameId'
      preLoaderRoute: typeof SpectateGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/storm': {
      id: '/puzzles/storm'
      path: '/puzzles/storm'
      fullPath: '/puzzles/storm'
      preLoaderRoute: typeof PuzzlesStormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/bot': {
      id: '/play/bot'
      path: '/play/bot'
      fullPath: '/play/bot'
      preLoaderRoute: typeof PlayBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings/$eco': {
      id: '/openings/$eco'
      path: '/openings/$eco'
      fullPath: '/openings/$eco'
      preLoaderRoute: typeof OpeningsEcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/write': {
      id: '/news/write'
      path: '/news/write'
      fullPath: '/news/write'
      preLoaderRoute: typeof NewsWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$tutorialId': {
      id: '/learn/$tutorialId'
      path: '/learn/$tutorialId'
      fullPath: '/learn/$tutorialId'
      preLoaderRoute: typeof LearnTutorialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/$category': {
      id: '/forums/$category'
      path: '/forums/$category'
      fullPath: '/forums/$category'
      preLoaderRoute: typeof ForumsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endgame/$id': {
      id: '/endgame/$id'
      path: '/endgame/$id'
      fullPath: '/endgame/$id'
      preLoaderRoute: typeof EndgameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching/dashboard': {
      id: '/coaching/dashboard'
      path: '/coaching/dashboard'
      fullPath: '/coaching/dashboard'
      preLoaderRoute: typeof CoachingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/$coachId': {
      id: '/coaches/$coachId'
      path: '/coaches/$coachId'
      fullPath: '/coaches/$coachId'
      preLoaderRoute: typeof CoachesCoachIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$slug': {
      id: '/clubs/$slug'
      path: '/clubs/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof ClubsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/$id': {
      id: '/challenge/$id'
      path: '/challenge/$id'
      fullPath: '/challenge/$id'
      preLoaderRoute: typeof ChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/$threadId': {
      id: '/assistant/$threadId'
      path: '/assistant/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AssistantThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orgs': {
      id: '/admin/orgs'
      path: '/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AdminOrgsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coaches': {
      id: '/admin/coaches'
      path: '/coaches'
      fullPath: '/admin/coaches'
      preLoaderRoute: typeof AdminCoachesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/puzzles/daily/$date': {
      id: '/puzzles/daily/$date'
      path: '/puzzles/daily/$date'
      fullPath: '/puzzles/daily/$date'
      preLoaderRoute: typeof PuzzlesDailyDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/thread/$threadId': {
      id: '/forums/thread/$threadId'
      path: '/forums/thread/$threadId'
      fullPath: '/forums/thread/$threadId'
      preLoaderRoute: typeof ForumsThreadThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$kind/$token': {
      id: '/embed/$kind/$token'
      path: '/embed/$kind/$token'
      fullPath: '/embed/$kind/$token'
      preLoaderRoute: typeof EmbedKindTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ai': {
      id: '/api/health/ai'
      path: '/api/health/ai'
      fullPath: '/api/health/ai'
      preLoaderRoute: typeof ApiHealthAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tick': {
      id: '/api/cron/tick'
      path: '/api/cron/tick'
      fullPath: '/api/cron/tick'
      preLoaderRoute: typeof ApiCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/v1/webhooks': {
      id: '/api/public/v1/webhooks'
      path: '/api/public/v1/webhooks'
      fullPath: '/api/public/v1/webhooks'
      preLoaderRoute: typeof ApiPublicV1WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/tournaments': {
      id: '/api/public/v1/tournaments'
      path: '/api/public/v1/tournaments'
      fullPath: '/api/public/v1/tournaments'
      preLoaderRoute: typeof ApiPublicV1TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/webhooks/retry-sweep': {
      id: '/api/public/v1/webhooks/retry-sweep'
      path: '/retry-sweep'
      fullPath: '/api/public/v1/webhooks/retry-sweep'
      preLoaderRoute: typeof ApiPublicV1WebhooksRetrySweepRouteImport
      parentRoute: typeof ApiPublicV1WebhooksRoute
    }
    '/api/public/v1/webhooks/$id': {
      id: '/api/public/v1/webhooks/$id'
      path: '/$id'
      fullPath: '/api/public/v1/webhooks/$id'
      preLoaderRoute: typeof ApiPublicV1WebhooksIdRouteImport
      parentRoute: typeof ApiPublicV1WebhooksRoute
    }
    '/api/public/v1/tournaments/sweep': {
      id: '/api/public/v1/tournaments/sweep'
      path: '/sweep'
      fullPath: '/api/public/v1/tournaments/sweep'
      preLoaderRoute: typeof ApiPublicV1TournamentsSweepRouteImport
      parentRoute: typeof ApiPublicV1TournamentsRoute
    }
    '/api/public/v1/embed/token': {
      id: '/api/public/v1/embed/token'
      path: '/api/public/v1/embed/token'
      fullPath: '/api/public/v1/embed/token'
      preLoaderRoute: typeof ApiPublicV1EmbedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/correspondence/sweep': {
      id: '/api/public/v1/correspondence/sweep'
      path: '/api/public/v1/correspondence/sweep'
      fullPath: '/api/public/v1/correspondence/sweep'
      preLoaderRoute: typeof ApiPublicV1CorrespondenceSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/classes/session': {
      id: '/api/public/v1/classes/session'
      path: '/api/public/v1/classes/session'
      fullPath: '/api/public/v1/classes/session'
      preLoaderRoute: typeof ApiPublicV1ClassesSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/users/$username/rating': {
      id: '/api/public/v1/users/$username/rating'
      path: '/api/public/v1/users/$username/rating'
      fullPath: '/api/public/v1/users/$username/rating'
      preLoaderRoute: typeof ApiPublicV1UsersUsernameRatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/users/$username/games': {
      id: '/api/public/v1/users/$username/games'
      path: '/api/public/v1/users/$username/games'
      fullPath: '/api/public/v1/users/$username/games'
      preLoaderRoute: typeof ApiPublicV1UsersUsernameGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/tournaments/$id/standings': {
      id: '/api/public/v1/tournaments/$id/standings'
      path: '/$id/standings'
      fullPath: '/api/public/v1/tournaments/$id/standings'
      preLoaderRoute: typeof ApiPublicV1TournamentsIdStandingsRouteImport
      parentRoute: typeof ApiPublicV1TournamentsRoute
    }
    '/api/public/v1/embed/token/$token': {
      id: '/api/public/v1/embed/token/$token'
      path: '/$token'
      fullPath: '/api/public/v1/embed/token/$token'
      preLoaderRoute: typeof ApiPublicV1EmbedTokenTokenRouteImport
      parentRoute: typeof ApiPublicV1EmbedTokenRoute
    }
    '/api/public/v1/classes/session/$id/students': {
      id: '/api/public/v1/classes/session/$id/students'
      path: '/$id/students'
      fullPath: '/api/public/v1/classes/session/$id/students'
      preLoaderRoute: typeof ApiPublicV1ClassesSessionIdStudentsRouteImport
      parentRoute: typeof ApiPublicV1ClassesSessionRoute
    }
    '/api/public/v1/classes/session/$id/set-position': {
      id: '/api/public/v1/classes/session/$id/set-position'
      path: '/$id/set-position'
      fullPath: '/api/public/v1/classes/session/$id/set-position'
      preLoaderRoute: typeof ApiPublicV1ClassesSessionIdSetPositionRouteImport
      parentRoute: typeof ApiPublicV1ClassesSessionRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCoachesRoute: typeof AdminCoachesRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminOrgsRoute: typeof AdminOrgsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCoachesRoute: AdminCoachesRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminOrgsRoute: AdminOrgsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiPublicV1TournamentsRouteChildren {
  ApiPublicV1TournamentsSweepRoute: typeof ApiPublicV1TournamentsSweepRoute
  ApiPublicV1TournamentsIdStandingsRoute: typeof ApiPublicV1TournamentsIdStandingsRoute
}

const ApiPublicV1TournamentsRouteChildren: ApiPublicV1TournamentsRouteChildren =
  {
    ApiPublicV1TournamentsSweepRoute: ApiPublicV1TournamentsSweepRoute,
    ApiPublicV1TournamentsIdStandingsRoute:
      ApiPublicV1TournamentsIdStandingsRoute,
  }

const ApiPublicV1TournamentsRouteWithChildren =
  ApiPublicV1TournamentsRoute._addFileChildren(
    ApiPublicV1TournamentsRouteChildren,
  )

interface ApiPublicV1WebhooksRouteChildren {
  ApiPublicV1WebhooksIdRoute: typeof ApiPublicV1WebhooksIdRoute
  ApiPublicV1WebhooksRetrySweepRoute: typeof ApiPublicV1WebhooksRetrySweepRoute
}

const ApiPublicV1WebhooksRouteChildren: ApiPublicV1WebhooksRouteChildren = {
  ApiPublicV1WebhooksIdRoute: ApiPublicV1WebhooksIdRoute,
  ApiPublicV1WebhooksRetrySweepRoute: ApiPublicV1WebhooksRetrySweepRoute,
}

const ApiPublicV1WebhooksRouteWithChildren =
  ApiPublicV1WebhooksRoute._addFileChildren(ApiPublicV1WebhooksRouteChildren)

interface ApiPublicV1ClassesSessionRouteChildren {
  ApiPublicV1ClassesSessionIdSetPositionRoute: typeof ApiPublicV1ClassesSessionIdSetPositionRoute
  ApiPublicV1ClassesSessionIdStudentsRoute: typeof ApiPublicV1ClassesSessionIdStudentsRoute
}

const ApiPublicV1ClassesSessionRouteChildren: ApiPublicV1ClassesSessionRouteChildren =
  {
    ApiPublicV1ClassesSessionIdSetPositionRoute:
      ApiPublicV1ClassesSessionIdSetPositionRoute,
    ApiPublicV1ClassesSessionIdStudentsRoute:
      ApiPublicV1ClassesSessionIdStudentsRoute,
  }

const ApiPublicV1ClassesSessionRouteWithChildren =
  ApiPublicV1ClassesSessionRoute._addFileChildren(
    ApiPublicV1ClassesSessionRouteChildren,
  )

interface ApiPublicV1EmbedTokenRouteChildren {
  ApiPublicV1EmbedTokenTokenRoute: typeof ApiPublicV1EmbedTokenTokenRoute
}

const ApiPublicV1EmbedTokenRouteChildren: ApiPublicV1EmbedTokenRouteChildren = {
  ApiPublicV1EmbedTokenTokenRoute: ApiPublicV1EmbedTokenTokenRoute,
}

const ApiPublicV1EmbedTokenRouteWithChildren =
  ApiPublicV1EmbedTokenRoute._addFileChildren(
    ApiPublicV1EmbedTokenRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalysisRoute: AnalysisRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  BillingRoute: BillingRoute,
  CorrespondenceRoute: CorrespondenceRoute,
  FairPlayRoute: FairPlayRoute,
  FeedRoute: FeedRoute,
  InsightsRoute: InsightsRoute,
  InviteRoute: InviteRoute,
  LeaderboardRoute: LeaderboardRoute,
  LobbyRoute: LobbyRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PolicyRoute: PolicyRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TvRoute: TvRoute,
  ApiChatRoute: ApiChatRoute,
  AssistantThreadIdRoute: AssistantThreadIdRoute,
  ChallengeIdRoute: ChallengeIdRoute,
  ClubsSlugRoute: ClubsSlugRoute,
  CoachesCoachIdRoute: CoachesCoachIdRoute,
  CoachingDashboardRoute: CoachingDashboardRoute,
  EndgameIdRoute: EndgameIdRoute,
  ForumsCategoryRoute: ForumsCategoryRoute,
  LearnTutorialIdRoute: LearnTutorialIdRoute,
  LessonsIdRoute: LessonsIdRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsWriteRoute: NewsWriteRoute,
  OpeningsEcoRoute: OpeningsEcoRoute,
  PlayGameIdRoute: PlayGameIdRoute,
  PlayBotRoute: PlayBotRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  PuzzlesStormRoute: PuzzlesStormRoute,
  SpectateGameIdRoute: SpectateGameIdRoute,
  StudyStudyIdRoute: StudyStudyIdRoute,
  TacticsThemeRoute: TacticsThemeRoute,
  TournamentsIdRoute: TournamentsIdRoute,
  AssistantIndexRoute: AssistantIndexRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  CoachesIndexRoute: CoachesIndexRoute,
  EndgameIndexRoute: EndgameIndexRoute,
  ForumsIndexRoute: ForumsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  OpeningsIndexRoute: OpeningsIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  PuzzlesIndexRoute: PuzzlesIndexRoute,
  SpectateIndexRoute: SpectateIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
  TacticsIndexRoute: TacticsIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  ApiCronTickRoute: ApiCronTickRoute,
  ApiHealthAiRoute: ApiHealthAiRoute,
  EmbedKindTokenRoute: EmbedKindTokenRoute,
  ForumsThreadThreadIdRoute: ForumsThreadThreadIdRoute,
  PuzzlesDailyDateRoute: PuzzlesDailyDateRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicV1TournamentsRoute: ApiPublicV1TournamentsRouteWithChildren,
  ApiPublicV1WebhooksRoute: ApiPublicV1WebhooksRouteWithChildren,
  ApiPublicV1ClassesSessionRoute: ApiPublicV1ClassesSessionRouteWithChildren,
  ApiPublicV1CorrespondenceSweepRoute: ApiPublicV1CorrespondenceSweepRoute,
  ApiPublicV1EmbedTokenRoute: ApiPublicV1EmbedTokenRouteWithChildren,
  ApiPublicV1UsersUsernameGamesRoute: ApiPublicV1UsersUsernameGamesRoute,
  ApiPublicV1UsersUsernameRatingRoute: ApiPublicV1UsersUsernameRatingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
